function team02_rep11
% rep-11
    [~, bytes, packets, ip_s, ip_d] = read_custom_csv('global_last10years.csv');

    function result = correlation(a, b)
        result = unique(min(corrcoef(a, b)));
    end
    
    names = { ...
        'Bytes <-> Packets', 'Bytes <-> IPs', 'Bytes <-> IPd', ...
        'Packets <-> IPs', 'Packets <-> IPd', 'IPs <-> IPd' ...
    };
    correlations = [ ...
        correlation(bytes, packets), correlation(bytes, ip_s), ...
        correlation(bytes, ip_d), correlation(packets, ip_s), ...
        correlation(packets, ip_d), correlation(ip_s, ip_d) ...
    ];
    [minimum_coeff, idx] = min(correlations);
    fprintf('Minimum linear correlation coeff: %f (%s)\n', minimum_coeff, names{idx});

    names_signal = {'Bytes', 'Packets', 'IPd', 'IPs'};
    means = [ ...
        mean([correlations(1), correlations(2), correlations(3)]), ...
        mean([correlations(1), correlations(4), correlations(5)]), ...
        mean([correlations(3), correlations(5), correlations(6)]), ...
        mean([correlations(2), correlations(4), correlations(6)])
    ];
    [~, idx_signal] = min(means);
    fprintf('Signal with lower correlation than others: %s\n', names_signal{idx_signal});
end
